//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace l2g.Entities.DataEntities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class l2g_tbl_UserDetails
    {
        [Key]
        public int UserDetailsId { get; set; }
        public int UserId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public System.DateTime DOB { get; set; }
        public string Contact { get; set; }
        public int HouseNo { get; set; }
        public string Street { get; set; }
        public string PIN { get; set; }
        public string Town { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
    
        public virtual l2g_tbl_User l2g_tbl_User { get; set; }
    }
}
