//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace l2g.Entities.DataEntities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class l2g_tbl_UserEmployeementDetails
    {
        [Key]
        public int UserId { get; set; }
        public string Company { get; set; }
        public int Salary { get; set; }
        public int CreditScore { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<int> EmployeeStatusId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public int UserEmployeementDetails { get; set; }

        public virtual l2g_tbl_Contract l2g_tbl_Contract { get; set; }
        public virtual l2g_tbl_EmployeeStatus l2g_tbl_EmployeeStatus { get; set; }
        public virtual l2g_tbl_User l2g_tbl_User { get; set; }
    }
}
