//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace l2g.Entities.DataEntities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class l2g_tbl_Quote
    {
        [Key]
        public int QuoteId { get; set; }
        public int UserId { get; set; }
        public int CarId { get; set; }
        public int MileageId { get; set; }
        public int MonthId { get; set; }
        public int Price { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
    
        public virtual l2g_tbl_Car l2g_tbl_Car { get; set; }
        public virtual l2g_tbl_Mileage l2g_tbl_Mileage { get; set; }
        public virtual l2g_tbl_PaybackTime l2g_tbl_PaybackTime { get; set; }
        public virtual l2g_tbl_User l2g_tbl_User { get; set; }
    }
}
